### ISSUE TITLE
ERR_REQUIRE_ESM while trying to start script

### ISSUE THREAD

**Issue by virtualb0x** [JamesHawkinss/discord-opsgenie-bot#6]
Hello. I've catched an error while truing to start
node .                                                                
                                                                   
```
/home/hostname/gitlab/discord-opsgenie-bot/helpers.js:4
const fetch = require('node-fetch');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/hostname/gitlab/discord-opsgenie-bot/node_modules/node-fetch/src/index.js from /home/hostname/gitlab/discord-opsgenie-bot/helpers.js not supported.
Instead change the require of index.js in /home/hostname/gitlab/discord-opsgenie-bot/helpers.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/hostname/gitlab/discord-opsgenie-bot/helpers.js:4:15)
    at Object.<anonymous> (/home/hostname/gitlab/discord-opsgenie-bot/index.js:5:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.3.0

```

Resolved by downgrading node-fetch@2.6.1   
Is it possible to fix it without downgrading?

**Comment by JamesHawkinss** [comment]
Hi there! node-fetch@2.6.1 is the required version, would have to update the code to support ES6 to support the newer versions of node-fetch. I have just updated the package.json to prevent this from occurring in the future. Thanks!
